### ISSUE TITLE
what's the meaning of "identified 2036 incorrect configurations"

### ISSUE THREAD

**Issue by Czw007** [BlackJocker1995/uavga#2]
In the Contributions part in this article, you said "We applied LGDFuzzer to a real-world flight control program
and identified 2, 036 incorrect configurations causing unstable flight states. We also verified 106 incorrect configurations on real-world drones and confirmed that these incorrect configurations cause trajectory deviations or drone crashes". In the EVALUATION part, you tested 20 configuration parameters, but what's the meaning of 2063 configuration errors and 106 incorrect configurations on real-world drones. I would appreciate it if you could answer this question.

**Comment by BlackJocker1995** [comment]
We said that we are testing 20 parameters rather than 20 configuration. These 20 parameters can make up different configurations. Like Configuration1 {A=1, B=1, C=1} and Configuration2 {A=1,B=2,C=3}.

Sender: ***@***.***>

In the Contributions part in this article, you said "We applied LGDFuzzer to a real-world flight control program
and identified 2, 036 incorrect configurations causing unstable flight states. We also verified 106 incorrect configurations on real-world drones and confirmed that these incorrect configurations cause trajectory deviations or drone crashes". In the EVALUATION part, you tested 20 configuration parameters, but what's the meaning of 2063 configuration errors and 106 incorrect configurations on real-world drones. I would appreciate it if you could answer this question.

**Comment by Czw007** [comment]
> We said that we are testing 20 parameters rather than 20 configuration. These 20 parameters can make up different configurations. Like Configuration1 {A=1, B=1, C=1} and Configuration2 {A=1,B=2,C=3}. Sender: ***@***.***> In the Contributions part in this article, you said "We applied LGDFuzzer to a real-world flight control program and identified 2, 036 incorrect configurations causing unstable flight states. We also verified 106 incorrect configurations on real-world drones and confirmed that these incorrect configurations cause trajectory deviations or drone crashes". In the EVALUATION part, you tested 20 configuration parameters, but what's the meaning of 2063 configuration errors and 106 incorrect configurations on real-world drones. I would appreciate it if you could answer this question. — Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBlackJocker1995%2Fuavga%2Fissues%2F2&data=05%7C01%7C%7Cb02aad92729a4b57aa6a08da21fa9239%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637859657341993369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mP82zFuLAe7g641cJzhgj6o%2BbpXjO3It55b%2FcrpXorg%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADRXMHYZC7VTDAHK7EMZBZLVF2MSDANCNFSM5TYSUALA&data=05%7C01%7C%7Cb02aad92729a4b57aa6a08da21fa9239%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637859657341993369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Nl7xW3wgTVJ4jjgV8OxqKFAHTmGTQYHn01OOdiVj7Ao%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Did these different configurations are randomly make?

**Comment by BlackJocker1995** [comment]
If you want to understand how a configuration creates, you can explore the  **Searching Process** in section 3.4 Learning-Guided Mutation Searcher

**Comment by Czw007** [comment]
> If you want to understand how a configuration creates, you can explore the **Searching Process** in section 3.4 Learning-Guided Mutation Searcher

Thank you very much for your reply, section 3.4 is indeed a difficult part to understand, I will continue to read this part.
